### ISSUE TITLE
EditCommand Code Suggestions and Improvements

### ISSUE THREAD

**Issue by blanklogic** [AY2425S1-CS2103T-T09-1/tp#148]
### 1. **Refactoring for Code Readability and Maintainability**
   - **Constants for STATUS_APPLIED and STATUS_CLOSED**: These could be defined in an `enum StatusType` or similar to enhance type safety, readability, and avoid potential typos.

**Comment by uniqly** [comment]
Regarding the specificality in error messages for `EditCommand`, if you input the wrong format for a particular field the app does remind you (eg: "Phone numbers should only contain numbers, and it should be at least 3 digits long"), so I do not think that is an issue.

**Comment by blanklogic** [comment]
> Regarding the specificality in error messages for `EditCommand`, if you input the wrong format for a particular field the app does remind you (eg: "Phone numbers should only contain numbers, and it should be at least 3 digits long"), so I do not think that is an issue.

Noted on this and made changes to this issue.
