### ISSUE TITLE
EditCommand Case Sensitivity in Duplicate Detection

### ISSUE THREAD

**Issue by blanklogic** [AY2425S1-CS2103T-T09-1/tp#150]
# **Case Sensitivity in Duplicate Detection**
   - **Severity**: Medium
   - **Description**: Duplicate detection in `isSameCompany()` may not consider case insensitivity. This could lead to user confusion if a company like "Google" is added twice with different cases. e.g. "Google" and "google".

**Comment by uniqly** [comment]
@blanklogic I think this should be a bug related to `AddCommand` rather than `EditCommand` since users should not be allowed to add companies with the same name but different cases and that editing the name of a company to the same name but with different casing is a legitimate use case (eg: "GOOGLE" -> "Google")

**Comment by blanklogic** [comment]
> @blanklogic I think this should be a bug related to `AddCommand` rather than `EditCommand` since users should not be allowed to add companies with the same name but different cases and that editing the name of a company to the same name but with different casing is a legitimate use case (eg: "GOOGLE" -> "Google")

In that case, would this be a problem for both `AddCommand` and `EditCommand` where for `EditCommand`'s case, editing an existing company 'B' to a similar name of company 'A' like 'a'?

**Comment by uniqly** [comment]
> In that case, would this be a problem for both `AddCommand` and `EditCommand` where for `EditCommand`'s case, editing an existing company 'B' to a similar name of company 'A' like 'a'?
Currently if you try to edit a company's name to another company, it does not allow that. At the same time, it also allows you to edit the name to anything (that is not taken by other companies)
