### ISSUE TITLE
EditCommand UI Long Input Edge Cases

### ISSUE THREAD

**Issue by blanklogic** [AY2425S1-CS2103T-T09-1/tp#151]
# **Long Input Edge Cases**
   - **Severity**: Low
   - **Description**: Currently, there is no handling for long inputs that could affect UI. If inputs like very long names, addresses, or tags cause layout issues, the impact might be minor (e.g., cut-off text) but still a potential issue.

**Comment by uniqly** [comment]
I also think that this is not really an issue since the app does give appropriate error messages for when these fields are missing.
