### ISSUE TITLE
[PE-D][Tester D] No warnings shown with names that differ from existing names only by white space

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T09-1/tp#233]
As per this excerpt from the 2103 website:![image.png](https://raw.githubusercontent.com/ZShunRen/ped/main/files/9bc0ad42-7c32-47ec-8b68-f5eb8cbd5a07.png)

There is no warning displayed to users when a new name is given, that only differs from an existing name by white spaces. 
![whitespace.png](https://raw.githubusercontent.com/ZShunRen/ped/main/files/a7525ab3-bc5a-4ef7-94ce-f4fa22328746.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ZShunRen/ped#5

**Comment by uniqly** [comment]
@AY2425S1-CS2103T-T09-1/developers Add this as a known issue/ planned enhancement
