### ISSUE TITLE
[PE-D][Tester C] Explanation does not match purpose of diagram

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T09-1/tp#251]
![image.png](https://raw.githubusercontent.com/Soumyadip-cmd/ped/main/files/ef23b7d9-f195-467c-a340-9e399dbc16fa.png)

Explanation says that it displays an activity diagram that explains roughly what happens when a user tries to add an application but the diagram is for updating application. Also there is a spelling mistake in application.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Soumyadip-cmd/ped#3

**Comment by uniqly** [comment]
Resolved by #226

**Comment by uniqly** [comment]
@AY2425S1-CS2103T-T09-1/developers fix typo, `tries to add` -> `tries to update`
