### ISSUE TITLE
[PE-D][Tester D] Missing features that correspond to user stories.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T09-1/tp#258]
Referring to the user stories that pertain to sorting:![userstories.png](https://raw.githubusercontent.com/ZShunRen/ped/main/files/9290d073-61c0-499b-a900-24427e3029e0.png)

There are no current or planned features that will address this user story.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: ZShunRen/ped#10

**Comment by uniqly** [comment]
@AY2425S1-CS2103T-T09-1/developers I think we can add some to our planned enhancements or remove unnecessary user stories and add the user stores that we have implemented but not stated.

**Comment by uniqly** [comment]
There is a missing user story for the favourite and unfavourite commands

**Comment by uniqly** [comment]
There is a missing user story for finding companies by tags and names of its applications
