### ISSUE TITLE
[PE-D][Tester D] Email attribute doesn't match definition of valid emails

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T09-1/tp#271]
Referring to the wikipedia [article] (https://en.wikipedia.org/wiki/Email_address) on emails, the santisation check on email. 

For instance,  the example `".John.Doe"@example.com` is an invalid email, but it should be a valid email:
![email.png](https://raw.githubusercontent.com/ZShunRen/ped/main/files/d2ff3f69-b34b-4ea8-ae73-7706369e9f42.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ZShunRen/ped#12

**Comment by uniqly** [comment]
Good catch! But I think it is reasonable to expect that user only comes across the unquoted email format (which is also typically the only format accepted by email service providers).

**Comment by uniqly** [comment]
Closed since not in scope.
